# fly.toml app configuration file generated for long-breeze-6908 on 2023-09-01T22:41:09-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "long-breeze-6908"
primary_region = "dfw"
console_command = "/code/manage.py shell"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
