# Generated by Django 4.2.3 on 2023-09-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_pastryrecipe_category_pastryrecipe_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastryrecipe',
            name='category',
            field=models.CharField(choices=[('CC', 'Cakes and Cupcakes'), ('PT', 'Pies and Tarts'), ('CB', 'Cookies and Biscuits'), ('Pastries and Puff Pastry', 'Pastries and Puff Pastry'), ('FD', 'Frozen Desserts'), ('PC', 'Puddings and Custards'), ('FR', 'Fruit-based Desserts'), ('ID', 'International Desserts'), ('OT', 'Other Desserts')], default='OT', max_length=30),
        ),
    ]
