# Generated by Django 4.2.3 on 2023-09-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_pastryrecipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastryrecipe',
            name='category',
            field=models.CharField(choices=[('Cakes and Cupcakes', 'Cakes and Cupcakes'), ('Pies and Tarts', 'Pies and Tarts'), ('Cookies and Biscuits', 'Cookies and Biscuits'), ('Puff Pastry', 'Puff Pastry'), ('Frozen Desserts', 'Frozen Desserts'), ('Puddings and Custards', 'Puddings and Custards'), ('Fruit-based Desserts', 'Fruit-based Desserts'), ('International Desserts', 'International Desserts'), ('OT', 'Other Desserts')], default='Cakes and Cupcakes', max_length=30),
        ),
    ]
